### ISSUE TITLE
MeasurementOrFact

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/material-sample#19]
# Current Darwin Core Placement/Definition

https://dwc.tdwg.org/terms/#measurementorfact

this term is a **class**

## Defintion
A measurement of or fact about an rdfs:Resource (http://www.w3.org/2000/01/rdf-schema#Resource).

## Examples
The weight of an organism in grams. The number of placental scars. Surface water temperature in Celsius.

## Comments
Resources can be thought of as identifiable records or instances of classes and may include, but need not be limited to dwc:Occurrence, dwc:Organism, dwc:MaterialSample, dwc:Event, dwc:Location, dwc:GeologicalContext, dwc:Identification, or dwc:Taxon.

**Comment by dagendresen** [comment]
Recall that the [OBIS extended measurement or fact](https://rs.gbif.org/extension/obis/extended_measurement_or_fact.xml) (eMoF) extension added occurrenceID to the eMoF, because of the need to connect (different) MoF records in the same DwCA to both events (Event as core and eventID as star schema entity) and to occurrences (using the occurrenceID added to eMoF). Following this logic the eMoF need also materialSampleID (and organismID)?

If maybe in a possibly (future?) larger restructuring of the data exchange format we maybe want to propose that there is no core (?) (and no star schema ???) how would one declare what entity would the [MoF](https://rs.gbif.org/extension/dwc/measurements_or_facts.xml) connect to? Using the [ResourceRelationship](https://rs.gbif.org/extension/dwc/resource_relation.xml)?

**Comment by dr-shorthair** [comment]
Closely related to https://www.w3.org/TR/vocab-ssn/#SOSAObservation 
* `sosa:hasResult` == `dwc:measurementValue` + `dwc:measurementUnit`
* `sosa:observedProperty` == `dwc:measurementType`
* `sosa:madeBySensor` == `dwc:measurementDeterminedBy`
* `sosa:usedProcedure` == `dwc:measurementMethod`
* sosa:resultTime` or `sosa:phenomenonTime` == `dwc:measurementDeterminedDate` 

Note SOSA also has `sosa:phenomenonTime` (the time the value relates to the entity-of-interest) is recorded separately to the `sosa:resultTime` which is when all data processing was completed. 

SOSA also has `sosa:featureOfInterest` which points to the target/subject of the `MeasurementOrFact`. 
'Feature' is a funny word inherited from GIS. 'Entity' is more general. 

'Observer' is probably a better term than 'Sensor' which implies only the mechanical kind.

**Comment by dagendresen** [comment]
@dr-shorthair if I understand sos:Observation correctly, sosa:hasFeatureOfInterest connects to the sosa:FeatureOfInterest in the same manner as the occurrenceID in the OBIS eMoF connects the measurement to an Occurrence as the subject of the measurement.

Which was my thought exactly, that maybe the Darwin Core MoF also needs a connector to the class that is the subject of the measurement --- because in the most common use of DwC the de-normalized simple Darwin Core (DwCA) one cannot readily assume that this is the core record in the middle of the star schema.

Something like a _dwc:measurementResourceID_ (?)

Or maybe simply deprecate MoF and use sos:Observation instead ???

**Comment by dr-shorthair** [comment]
Not suggesting that you remove `MoF`, unless there is a plan for a wholesale refactoring of DWC or DWC-SW, which I don't think is on the table. My point was more to 
(a) show that `MoF` is well conceived, since it aligns with other accepted standards
(b) perhaps point to a couple of holes that might be usefully filled.

**Comment by dr-shorthair** [comment]
Also see https://github.com/tdwg/material-sample/issues/11#issuecomment-941937381 which includes diagrams of information-models for (i) acts of observation (ii) acts of sampling - showing how they can both be interpreted in the same way. 

---

In [W3C SSN/SOSA](https://www.w3.org/TR/vocab-ssn/) these are modeled in a way that can be interpreted as [types of prov:Activity](https://www.w3.org/TR/vocab-ssn/#PROV_Alignment), specifically

<img src="https://www.w3.org/TR/vocab-ssn/images/observation-prov.png" alt="Observation-Prov-alignment" width="350"/><img src="https://www.w3.org/TR/vocab-ssn/images/sampling-prov.png" alt="Sampling-Prov-alignment" width="350"/>

(SOSA calls it a 'feature-of-interest' instead of 'entity-of-interest'.)
(`Sensor` should be renamed `Observer`.)

**Comment by Jegelewicz** [comment]
closing as out of scope for this Task Group
