### ISSUE TITLE
Primary Deliverable - MaterialSample definition

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/material-sample#2]
## Current Definition

http://rs.tdwg.org/dwc/terms/MaterialSample

> A physical result of a sampling (or subsampling) event. In biological collections, the material sample is typically collected, and either preserved or destructively processed.

Please suggest changes/improvements in this issue.

See also https://github.com/tdwg/material-sample/blob/main/primary_deliverable/MaterialSample.markdown

See also [MaterialSample terms Google Sheet](https://docs.google.com/spreadsheets/d/1KWWGF6p4BREoDZy7HeVbC3NEFIMzNbA78sMsOR6uX_k/edit#gid=0&range=B2)

**Comment by tucotuco** [comment]
Additional related commentary in https://github.com/tdwg/material-sample/issues/3#issuecomment-903305155.

**Comment by Jegelewicz** [comment]
From https://github.com/tdwg/material-sample/issues/3#issuecomment-904297225

> OK, so what is a MaterialSample then? I am much more fuzzy about this. It seems that the two necessary conditions are being a material thing (e.g. images don't qualify), and being sampled from something. There is no assumption that it is derived from an organism as air or water samples free of organisms could be material samples. I guess that it has something similar to the accession component that I used to define specimens, although I'm not sure about that. If the material is not destructively sampled, the DwC definition implies that it should be preserved, although I'm unsure that is the case for every material sample, e.g. ones that may be thrown out after measurements or documentation is complete. There are also samples that were obviously sampled for the purpose of being destroyed - in my mind that is a difference from specimens since I don't think specimens are generally intended to be destroyed intentionally. So a material sample can be derived from an organism, but doesn't have to be. A material sample can be a specimen, but doesn't have to be. A specimen does not have to be a material sample -- clearly the Bicentennial Oak was never the result of a sampling event. A material sample might be preserved but doesn't have to be. Honestly, the definition of MaterialSample is so fluid that it is hard for me to see why it is useful to assert that something is an instance of it.

**Comment by dr-shorthair** [comment]
Also see https://github.com/tdwg/material-sample/issues/3#issuecomment-905030133: 

- a sample is representative of a larger thing. It is the result of an act of sampling (see https://www.w3.org/TR/vocab-ssn/#Sampling). Usually the intention is that it will be used for observations
- a specimen is an accessioned thing. Usually the intention is that it is available for observations.

A sample is not necessarily a material thing, social science samples are often not.
A sample might not be accessioned (particularly if it will be destroyed as part of some analytical process).

I think specimens are always material things.

**Comment by Jegelewicz** [comment]
https://github.com/tdwg/material-sample/issues/3#issuecomment-905108910

> Instances of MaterialSample are aggregates of physical material that are extracted ("collected") from the natural environment, and held in the custody of humans. Following the suggestion of @baskaufs that instances of a class should be defined by shared properties, these are physical items that may be preserved or destroyed, curated or accessioned, borrowed and loaned, subsampled or aggregated to yield new instances of MaterialSample, and otherwise cared for and/or maintained in some way by humans.

**Comment by deepreef** [comment]
Thanks for bringing that here! (And sorry for not thinking to do so myself).  Just to be clear, though, I was not intending to propose a formal definition; but rather I tried to capture my own thinking of what a `MaterialSample` is, in "plain English"(ish).

**Comment by Jegelewicz** [comment]
But it is good!

**Comment by smrgeoinfo** [comment]
a materialSample is an object separated from the material world, intended to be representative of some sampled feature. 

Samples are typically collected with the intention of making measurements/observations on the sample that will characterize the sampled feature. 
A sample might undergo some curation process and become a specimen (as well as a sample). 
A MaterialSample might be an aggregation of material unified by containment in some container, e.g. rock powder in a bag, water in a bottle, blood in a syringe. 
A MaterialSample might be a self-connected object like a leaf from a tree, or a piece of rock from an outcrop.
MaterialSamples can be derived from other material samples, e.g. the legs from a grasshopper, or zircon crystals from a rock sample. 
The sampled feature can be hierarchical; e.g. a material sample might be a leaf from a particular oak tree (organism) considered the sampled feature, or the sampled feature might be considered the taxon to which that individual oak tree belongs.

**Comment by dr-shorthair** [comment]
> A sample might undergo some curation process and become a specimen (as well as a sample).

Maybe: "A sample might undergo some curation _and accession_ process and become a specimen (as well as a sample)."

**Comment by RogerBurkhalter** [comment]
I recall a previous comment about accession and asked our Registrar about the legal meaning, which is, in part, legal ownership. Some samples and specimens we can never own, i.e. fossils/archaeological remains from US Federal lands, other countries have similar laws, but we do reposit them. I suggest "accession or reposit".

**Comment by Jegelewicz** [comment]
> Wouldn't the controlled vocabulary examples listed for environmentalMaterial also be among the controlled vocabulary examples for materialSampleType?

I would think so.

**Comment by dr-shorthair** [comment]
Is 'inanimate' a problem?

**Comment by Jegelewicz** [comment]
> Is 'inanimate' a problem?

I would think so - a gorilla in the zoo, a tree in the botanic garden. Thanks for pointing that out! So now what.....I need to have a weekend!

**Comment by dr-shorthair** [comment]
> "Sample" implies that it's the subset of all physical things that humans capture or care for in some way. 

I don't find that very helpful. It is also not very consistent with the various bits of discussion above. 
- things that are _captured and cared-for_ are _specimens_ 
- things that are subsets, or are in some other way representative, of _some other identifiable discrete_ thing are _samples_. 

The sentence quoted conflates these concerns in a rather confusing way. 

I believe the concern here is to recognize that, if 'sample' and 'specimen' are both roles, and are somewhat independent of each other, then we need to identify the parent class of 'material things', some of which are also samples, some of which are specimens, and some of which are both.

**Comment by deepreef** [comment]
> I don't find that very helpful. It is also not very consistent with the various bits of discussion above.
> - things that are captured and cared-for are specimens
> - things that are subsets, or are in some other way representative, of some other identifiable discrete thing are samples.
> The sentence quoted conflates these concerns in a rather confusing way.

Fair enough -- that sentence was written hastily -- which is why I was a bit more careful in the wording of the definition text:
> Any physical object (as defined in Dublin Core), or discrete portion of a physical object, or aggregate set of physical objects, that is/are collected, processed, analyzed, managed, or curated by humans.

So... replace "humans capture or care for in some way" with "collected, processed, analyzed, managed, or curated by humans".  Not sure if that is any better, though.

> I believe the concern here is to recognize that, if 'sample' and 'specimen' are both roles, and are somewhat independent of each other, then we need to identify the parent class of 'material things', some of which are also samples, some of which are specimens, and some of which are both.

I think we get way too hung up on the semantics of "specimen" (as a noun?) and "sample" (as a verb?).  Both of these terms have different meanings to different people, and different definitions in different contexts.  Of the two (specimen and sample), my sense is that "sample" probably carries less misinterpretation-potential baggage.  But maybe that's just me?

In any case, the good news is that we don't need to define "specimen", and we don't need to define "sample", because neither of those terms, by themselves, is a DwC term.  What we do need to do is define `MaterialSample` as a term.  If either "Material" or "Sample" as part of that term are so misleading and problematic that they create excessive confusion, then perhaps we need to come up with a new term.  Personally, I think the costs of establishing a new term are greater than the costs of potential misinterpretation of pre-conceived notions of what "Material" or "Sample" somehow implies, so my preference, still, is to keep the term "MaterialSample".

So... I agree... the phrase "humans capture or care for in some way" was unhelpful.  But I'm curious: what to folks think of the actual wording I proposed for the definition of `MaterialSample` (above)?

> http://purl.org/dc/dcmitype/PhysicalObject would be fine, except for the 'inanimate' qualifier :-(

I agree that "inanimate" is problematic, but I think a bigger problem is the scope.  I do not think that `dwc:MaterialSample` should adopt a definition that defines the scope as broadly as `dc:PhysicalObject`.  I do see instances of  `dwc:MaterialSample` as representing a subset (subclass) of `dc:PhysicalObject`, but I don't see the two concepts as congruent.  Why?  because not all instances of `dc:PhysicalObject` are "collected, processed, analyzed, managed, or curated by humans"; and my sense is that we would like to confine `dwc:MaterialSample` to that more limited scope of physical things.

**Comment by deepreef** [comment]
Ok, yes -- that sounds right to me.  What are some examples of `AccessionedThing` that are not also instances of `MaterialSample`?  If there are none, then wouldn't this additional class be:

`dwc:AccessionedThing rdfs:subClassOf dwc:MaterialSample`

?

**Comment by dr-shorthair** [comment]
Sorry - I already edited my previous comment since I saw that our agreement was less complete than I'd originally thought. But I think your response is undamaged by that. 

The key property of a `Sample` is its relationship to the identifiable, discrete thing which is sampled - the `isSampleOf` relation. Until you know what that is then it could be argued that an object in a collection is merely a curiosity. 

Furthermore, some artefacts can be simultaneously samples of more than one thing - taxa of more than one rank; an ecosystem; the set of specimens in a single collection, etc. But there would often be a scientific purpose for collecting a sample, which would point to its 'primary' source. 

Note that by being a bit careful about the definition of 'Sample' in general, we can see `MaterialSample` as also having siblings in the social science world:
```turtle
dwc:MaterialSample rdfs:subClassOf science:Sample .

socsci:PopulationSample rdfs:subClassOf science:Sample .

socsci:PopulationSample rdfs:subClassOf science:Population .
```

Of course the PopulationSample would never be accessioned by a museum, and arguably is not a PhysicalObject either.

**Comment by dr-shorthair** [comment]
Multiple-inheritance is a bit clunky - I find set-intersection a better way of thinking of it. 
![image](https://user-images.githubusercontent.com/608303/137671713-afa6f869-e1b3-43de-ae2d-e055ae34042f.png)

**Comment by dagendresen** [comment]
I only want to add that specimens (collection items) have a very special role in our community as also demonstrated with (current) representation in Darwin Core by no less than three classes (PreservedSpecimen, FossilSpeciman, and LivingSpecimen). If we want to suggest deprecating all these three to be merged into MaterialSample, we might want to make sure to include the word specimen somewhere in the definition or at minimum least in the usage comments. To reduce any confusion museum collection curators might get into. (I personally struggle to see any major harm in maybe consider keeping a PreservedSpecimen class, or similar, because this type of thing is so central in our community.)

**Comment by dr-shorthair** [comment]
@Jegelewicz I reached out to @tombaker from DCMI again, and the suggestion was to look at [dcterms:PhysicalResource](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/PhysicalResource) rather than [dctype:PhysicalObject](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/dcmitype/PhysicalObject). This is partly because of the unfortunate (and probably unintentional) 'inanimate' qualifier, but mostly because the [DCMI Type vocabulary](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#section-7) is a bit of a historical dead-end, compared with the classes in the main DC-Terms vocabulary.

**Comment by Jegelewicz** [comment]
HMMMMM. Now I am going to muddy the water! This makes me think that perhaps we are lumping things together which shouldn't be? Maybe `LivingSpecimens` are never also `MaterialSamples`? Perhaps, they should be Agents http://purl.org/dc/terms/Agent just as discussed [here](https://github.com/tdwg/material-sample/issues/11#issuecomment-933528856)?

**Comment by dr-shorthair** [comment]
@deepreef when you say `Organism` != `MaterialSample` do you mean 
(a) the classes are disjoint; the set-intersection is empty, there are no Organisms that are also MaterialSamples
(b) the classes are not identical; there are Organisms that are not MaterialSamples, and there are MaterialSamples that are not Organisms, but there may be things that are both ?

**Comment by dr-shorthair** [comment]
I fear we are getting tangled up on the labels which is obscuring the fully clarification of the descriptions and roles. 
I think we have been talking about the following classifications (not exhaustive). I've attempted to break them down into fairly primitive concerns. These are NOT all disjoint (though some pairings are):

(i) immaterial things
(ii) material things
(iii) dead things
(iv) living things
(v) things with agency (i.e. that are _active_ participants in processes and activities)
(vi) things that are intended to be representative of some larger or less accessible thing
(vii) things that are managed as part of an ongoing collection or archive
(viii) preserved things
- (ix) things preserved naturally 
- (x) things preserved artificially

We each use specific names to denote specific classes. The named classes are often intersections of two or more of these concerns. The same class (or class intersection) may be denoted by different names in different communities, even within the TDWG orbit.  I'll give my names in a separate comment, so as not to bias other responses.

**Comment by stanblum** [comment]
Thanks for those clarifications, Rich.  I think we agree.  Not all organisms become material-samples, and not all (biodiversity) material-samples are (whole) organisms, so the one-to-one correspondence that can exist in some cases is *not* a class-subclass relationship.  I also want to argue that organism and (biodiversity) material-samples should be recognized as distinct things because our samples **infer the existence (or former existence)** of organisms and its properties.  Samples tell us about organisms, and by inference populations and taxa.

**Comment by Jegelewicz** [comment]
> Side note: I'm imagining that the example values above for materalSampleType are subtypes of PreservedSpecimen.

Calling "whole organism" a subtype of PreservedSpecimen seems pretty darn confusing!

**Comment by stanblum** [comment]
Back on Oct 17, 2021 [I mentioned](https://github.com/tdwg/material-sample/issues/2#issuecomment-945343933) that I think "Material Sample" entered the DwC discourse through the BioCollections Ontology (BCO).  A change in BCO I wasn't aware of until yesterday is that BCO has now deprecated the "Material Sample" class (made it an obsolete class), and instead have adopted a term/class from a larger ontology,  the Ontology for Biomedical Investigations (OBI)(!):

>  obi:specimen: A material entity that has the specimen role.

This combines several of the notions we've been discussing: a material entity that is the result of a material sampling process and has been taken (collected and understood) to represent some larger entity (thing, population, community) in further study or analysis.

Also deprecated in BCO were the subclasses of Material Sample, including: preserved-, living-, and fossil-specimen.

I thought it was noteworthy that having taken materialSample from BCO to create a superclass for all the different kinds of things we manage in the biocollections community, the DwC is now (still) using "material sample," while the BCO is now using "obi:specimen."  Should we follow?  Would it be appropriate for us to 1) incorporate the obi:specimen term in DwC, or 2) mint our own specimen term, dwc:specimen, and paraphrase their definition while including a "crosslink", like:

> dwc:specimen : is "same-as" or "comparable-to" : obi:specimen

The argument for the second option being that DwC is currently a bag of terms and doesn't support reasoning, which OBI (an OWL ontology) does. In other words, they aren't the same kinds of standards, so incorporating an OBI term in DwC isn't the right thing to do. The better practice might be just to reference obi:specimen in some appropriate way.  I'll defer to others with more experience.

Or, given that we also want to include environmental samples in DwC (for metagenomic analysis), should we just retain the term "material sample", because most people wouldn't think of an environmental sample as a "specimen."

**Comment by smrgeoinfo** [comment]
looks like OBI still has ['material sample'](http://purl.obolibrary.org/obo/OBI_0000747 ), defined as _'A material entity that has the material sample role'_, which is a subclass of [specimen](http://purl.obolibrary.org/obo/OBI_0100051), '_A material entity that has the specimen role._'.  I don't see anything about deprecation (Last uploaded: January 10, 2022).  You'd be hard pressed to distinguish specimen from material sample given their definitions, so I can see why they'd get rid of one of them.

**Comment by deepreef** [comment]
Thanks, @stanblum!

Does OBI define the scope of “specimen role”?  And what other kinds of material entities (in the sense of OBI) are outside that scope?

I’m not in favor of changing dwc:MaterialSample to dwc:Specimen if they have essentially the same definition (for reasons articulated by @baskaufs  at an earlier zoom meeting).

**Comment by deepreef** [comment]
Sorry I missed the last session on this. One question and one comment:

Question: In the proposed new definition, is there a difference between "physical object" and "physical entity"?

Comment: The proposed examples seem a little animal-centric -- maybe a plant and a bacteria example would be good to add?  Also, maybe a better/more intuitive example of an "undetatched" instance of MS would be a fossil aggregate represented by a single physical rock with multiple embedded organisms.

Also... I hadn't considered the "undetatched" potential within a single organism in MaterialSample examples. Certainly examples of multiple organisms represented as a single colelctive object (aforementioned fossil; hermit crab+shell+anemone; etc.).  But I'd not considered the possibility of branding undetatched subcomponents of the same individual Organism as distinct MS instances. I guess that means that any given MS instance of a single organism could have near-infinite potential child instances, without any disarticulation action happening to the whole.  I don't have a problem with this, but the non-normative documentation should probably explain this a bit more, with an explanation that MS instances are minted when there is an informatic need to do so, and also including examples where there is an informatic need to track undetatched subcomponents of an object (e.g., the undetached leg of a dog).

**Comment by deepreef** [comment]
> I think the use of two different terms ("physical object" - "physical entity") can be defended to reflect that a subject of collection or observation will as a matter of necessity be spatially more confined than physical entities in general (the latter including, for example, all geese in the world, the taiga, Earth's atmosphere).

OK, thanks! That makes sense to me. But it wasn't immediately obvious (to me, at least) from the wording of the definition.  I think the wording of the definition can stay as it is, as long as the non-normative explanatory comments help folks understand the implications of the distinction (physical object vs. physical entity) -- as you suggest.

> Note that composition can also go the other way: each of a dinosaur skeleton's bones in a collection can be an instance of dwc:MaterialSample as can be the set of bones, even if they aren't physically associated in the collection.

Yes!  Definitely.  I think it's clear that aggregates of multiple disconnected MS items can be collectively bundled into a single umbrella/parent MS instance.  Whether or not those individual component items came from the same instance of Organism, or multiple Organism instances, shouldn't make any difference.

>  If that set of bones is incomplete, also the set of bones that potentially make up the whole skeleton could, IMO, be minted as another instance of dwc:MaterialSample satisfying certain informatic needs.

I guess so... but this almost sounds like advocation for accepting hypothetical/inferred physical objects within scope.  I don't immediately have anything against that, but I worry that it might be flirting with the edges of the MS scope a bit.  I'm thinking of the type specimen for *Nessiteras rhombopteryx*.  But in that case, the physical object is not hypothetical -- it's just that it might be an Organism, and it might (probably) be a rock.

**Comment by RogerBurkhalter** [comment]
In October 2020, we had a meeting of the Paleo "Happy Hour" on the topic of clusters/fossils on a slab and otherwise instances of what I refer to as "loanable objects" (cannot loan one without loaning all objects in or on a "container"). The list we came up with may be useful. We sub-divided the list into Natural Accumulations and Artificial or Anthropogenic Accumulations:

**Natural Accumulations:**
Fossil bearing rock rich in abundance
 - Death assemblage
 - Reefs
 - Transport/deposition, taphonomic
 - Condensed bed (slowed sediment or carbonate rate, i.e. more time in a thin horizon)_
Coquina or bonebed
Coal balls
Amber
Parts and counterparts
Articulated vertebrate remains
Epibionts
Fortuitous preservation (i.e. a benthic taxon preserved on a sessile taxon, just by chance, or a "last meal" preserved)

**Artificial or Anthropogenic Accumulations:**
Palynomorph slides (strew samples)
Diatom slides (strew samples)
SEM stubs
 _- Single taxon_ 
    - Single Locality
    - Multiple Localities 
 _- Multiple taxa_
    - Single Locality
    - Multiple Localities
Microfossil cavity slides or gridded cavity
 _- Single taxon_
    - Single Locality
    - Multiple Localities
 _- Multiple taxa_
    - Single Locality
    - Multiple Localities
Coal Ball Peels/Microfossil thin sections
 _- Single Locality
 _- Multiple Localities__

The antithesis of these examples for anthropogenic modification is serial thin sections or peels of an individual fossil, which would fall under the current definition of MaterialSample. What we discussed briefly are examples of display fossils that are composits of several individuals, usually vertebrate fossils, sometimes invertebrate or plant fossils. The point is that a wide variety of natural and anthropogenic objects are possible. This list was assembled from the Invertebrate Paleontology and Paleobotant collections at one museum.

**Comment by RogerBurkhalter** [comment]
I left these comments last night after two long weeks of interviewing Curator candidates for the collection I am CM for. I left these as examples of paleontology collection objects and the difficulties of fitting our collections into existing CMS and DwC models. Paleontology objects are rarely "as found", they routinely require some effort at initial preparation to further expose fossilized biological objects and then some means to preserve not only the object but the relationship between it and other associated objects found within the original sample (i.e. dwc:associatedOrganisms). However, consider for example a palynology sample: a quantity of rock is collected from a locality, transported to a lab, the rock is broken into smaller peices and placed in a jar for reserve and a subset is separated and further reduced to a coffee ground consistancy and stored, a subset of the ground sample is then placed in an acid resistant beaker and processed with HF for a day or more, washed and centrifuged. The processed "residue is then stored in a vial and a subset of the now processed residue further cleaned and pipetted onto a microscope slide cover slip, dried and flipped onto a microscope slide. When the slide is examined, you finally can see the objects collected, along with hundred to thousands of other co-occuance objects (dwc:associatedOrganisms). What is the MaterialSample, the original collected rock, the ground residue, the acid prepared residue, the microscope slide itself, or the pollen grain on the slide (that has a Linnean name and coordinates from an England finder)?

The original collected sample may have other fossil forms embedded within that would be destroyed by HF processing. Subsets may be processed by other acids (Formic, dilute HCl, Acetic, etc.) or reducuced and hand-picked under a binocular microscope to produce Conodonts, Foraminifera, Calcareous Nanofossils, or megafossils, etc.. Derivative samples may also be processed for non-biological data such as isotopes of strontium, carbon, oxygen, boron, etc. and/or radiometric dating. As such. I would see the original collected sample as the parentMaterialSample to maintain at least some relationship to all of the derivative biological and non-biological entities, with the processed samples as (what?) and the (identified and named) biological objectas the MaterialSample. Seems a lot of processed derivative samples either carry the same designation as the original parentMaterialSample, or are absorbed into dwc:preparations (that do not really fit as not a preservation method), and making the link between the parent and child somewhat muddy.  This is also very true of commercial CMS and why I use a database I created to keep these relationships and results discoverable. Mapping to DwC has always been a challenge (need more coffee).

Sorry for the long comments.

**Comment by tucotuco** [comment]
@RogerBurkhalter This kind of detailed use case is immensely useful. It highlights both the value of the concept of a parentMaterialSample (see https://github.com/tdwg/dwc/issues/344) and its limitations. By limitations, I mean, "What does it mean to be the parent?" I suspect we need a much richer way to relate materials, with something at the level of a ResourceRelationship where the nature of the relationship can be specified. In the [Diversifying the GBIF Data Model](https://tinyurl.com/diversifying-gbif-data) work, the model anticipates the relationships "part of" and "derived from" as well as a separate mechanism to establish membership in a material group that was developed for the OBIS Community Measurement use case, but that would also work for other purposes.

**Comment by deepreef** [comment]
@RogerBurkhalter :
> What is the MaterialSample, the original collected rock, the ground residue, the acid prepared residue, the microscope slide itself, or the pollen grain on the slide (that has a Linnean name and coordinates from an England finder)?

My answer: The MaterialSamples (plural) are: whatever units of physical material(s) warrant identification and associated metadata from an informatics perspective.

In other words, the decision of whether to mint a new `materialSampleID` value (=establish a `MaterialSample` instance) should be driven by a specific need to track information related to a particular unit of physical material.

Some use cases in my (non-fossil) world:
Whole fish is collected, fin-clip is removed and preserved separately (for DNA analysis), scale falls off body and is lost:
1) Whole specimen (voucher)
2) Tissue sample (parent=1)

In this case, I would not bother assigning a separate MS instance to the fish before its fin clip was removed (or scale lost); and I would not bother assigning a separate MS instance to the lost scale, because I have no informatic need to track either of those separately from the two MS instances I do mint.

Whole bird is collected, put in freezer, and accessioned/catalogued. Later, the skin is removed and prepared dry, the internal organs are preserved in alcohol, the skeleton is processed with the aid of dermestid beetles. Later still a subsection of tissue is removed from the preserved organs for DNA analysis.
1) Whole organism as frozen/accessioned/catalogued
2) Skin (parent = 1)
3) Internal organs in alcohol (parent = 1)
4) Skeleton (parent = 1)
5) Tissue for DNA (parent = 3)

In this case, I have an informatic need to track the whole organism prior to dissociation of parts (object that is accessioned and catalogued), so I do assign an MS instance to this.  I do not bother assigning MS instances to the blood and other tissue that ended up in the waste basket, not the tissue consumed & digested by the dermestid beetles, because I don't have an informatic need to track them. Because the tissue sample was subsequently removed from the alcohol-preserved organs, I treat it as a child of that MS (3), rather than a a direct child of the whole (1).  That way, the curation history of the tissue sample is more precisely/completely represented in the chain of preservation processes (e.g., in case the internal organs where first fixed in formalin, so I would then know that the derived tissue sample is not fit for purpose for DNA sequencing).

These are pretty straightforward examples in my mind.  Another straightforward example is if a feather is plucked from the skin and used for some purpose/preparation/whatever, in which case I would mint:
6) Feather (parent = 2).

But here's where it gets interesting, relative to the earlier discussion on "undetatched" MS children.  Suppose I photograph just the wing of the mounted skin.  Would I have a need/desire to mint a new MS instance for the wing, even though it is still physically part of the whole skin?  That way, I could make the subject of the image the wing alone, rather than the whole skin preparation.  But is that really good practice?  I honestly dunno.

In any case, I think the same basic logic ("Do I have an informatic need to track properties or relationships of a particular aggregate/unit of physical material?") would apply in the example you gave for which bits get distinct instances of MS.

**Comment by deepreef** [comment]
@tucotuco :
> I suspect we need a much richer way to relate materials, with something at the level of a ResourceRelationship where the nature of the relationship can be specified.

I've come around to applying that logic to *all* relationships within DwC.  In other words, whenever  there is an xxxID term/property within a DwC Class, I'm leaning towards representing those values not as direct properties of the root instance, but as instances of `ResourceRelationship`.

I think of this as a "semi-serialized" approach.  That is, literal values are treated as direct properties of DwC class instances (e.g., property "fields" to the class "tables"), but all "foreign key" property values are captured as an "octuple store" (eight terms organized in `dwc:ResourceRelationship`).

I have no idea whether this quasi-hybrid relational model/serialized model is practical or sensical, but it feels like a potentially practical middle-ground between the two different ways of representing data (i.e., tables & fields vs. triple-store).

**Comment by Jegelewicz** [comment]
Attendance at the 2022 working session included a lot of people who are not members of the Task Group and their primary concern was with the baggage that might be associated with "sample". 

> Mathias Dillen: This definition includes a physical photograph and a physical drawing of an organism or fossil, right?
> Carlos Martínez: I wouldn't consider those as part of a *material* *sample*, e.g., I don't sample a photograph, I take a soil sample in a bag
> Carlos Martínez: photographs and illustrations are "works" in the sense of the ZooCode
> Carlos Martínez: Samples come from *sampling*, e.g., collecting material things during a field trip / sampling event. A digital photograph is not a material sample. I think that we are confusing "collection objects" with material samples in the sense used by field biologists. I am a biologist and calling a photograph a material sample is counterintuitive (read wrong) to me.
> Deborah Paul: A herbarium sheet, sometimes only has an image on it.
> Carlos Martínez: A herbarium sheet is not a material sample, the plant on it is. If there is no plant and there is just a picture, there is no material sample on the sheet and the sheet is just a collection object.
> Carlos Martínez:	Things that are included in a material sample: the three main materials upon which scientific names of animals are based: 1) specimens, 2) fossils that are substitutions (replacements, impressions, moulds and casts) for the actual remains of animals, and 3) the fossilized work of animals (ichnofossils).

It was clear to me that people were looking for something that could encompass any physical material whether it was a "sample" or not if we hope to allow collections to use DarwinCore to share their objects. There was also discussion about the use of the term sample when associated with human remains. As I have first-hand experience attempting to remove "specimen" from everything in a CMS, I completely understand the concern. Notes from the session include this: “Sample” is problematic, consider “catalogueRecord”, “object”, “entity”, “unit”

> Mariel Campbell:	If we change the term to Material Object or Entity, and define it as a physical object, then an herbarium sheet with a physical photograph in it is indeed a Material Object. It can be barcoded and loaned.
> John Wieczorek:	“Entity” might not be so easy to understand. But then maybe it will force people to read the definition. ;-)
> Mariel Campbell:	It also avoids calling a part or representation of a human or named animal as an "object" which is an issue

It was also discussed that a "material" class should start with a "High-level distinction between material and information artefact" as this would mesh with the LatimerCore [baseTypeOfCollection](https://github.com/tdwg/rs.tdwg.org/blob/latimer/process/page_build_scripts/index.md#ltc_baseTypeOfCollection)

So - should we really be starting with the class MaterialEntity? Would this be equivalent to the Dublin Core PhysicalResource?

Term | PhysicalResource
-- | --
URI | http://purl.org/dc/terms/PhysicalResource
Label | Physical Resource
Definition | A material thing.
Type of Term | Class

I know this feels like a step backward.

> Steve Baskauf: I feel like we are plowing ground that was plowed a year ago in this group...

BUT as LatimerCore is currently in expert review and they cover a lot of things that crossover into material, I think we need to think deeply about this.

**Comment by Jegelewicz** [comment]
Term Change submitted - https://github.com/tdwg/dwc/issues/451

**Comment by Jegelewicz** [comment]
change complete - https://github.com/tdwg/dwc/issues/451
