### ISSUE TITLE
materialSampleID

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/material-sample#20]
## Current Definition

https://dwc.tdwg.org/terms/#dwc:materialSampleID

> An identifier for the MaterialSample (as opposed to a particular digital record of the material sample). In the absence of a persistent global unique identifier, construct one from a combination of identifiers in the record that will most closely make the materialSampleID globally unique.

Comments

> Recommended best practice is to use a persistent, globally unique identifier.

Please suggest changes/improvements in this issue.

**Comment by dagendresen** [comment]
I would also be opposed to moving a similar text to the usage comments. I think composite identifiers are really bad advice!

**Comment by deepreef** [comment]
> As a point of clarification: What do you think the prevailing attitude would be now towards pushing a distinction between the physical-object (<= material-sample <= preserved-specimen) and its digital catalog-record (=>information artifact)? The ID on the physical thing, our traditional catalog (aka accession# in botany), ties the specimen to the information record in the catalog (and is often reported in Material Examined of scientific publications); whereas the ID of the digital record containing data about the specimen can be made to comply with modern requirements (persistent, resolvable, globally unique). I added this distinction to the second figure I posted on a wiki page. Is this still be viewed as an unnecessary complication, or is there growing compliance in creating and using GUIDs for the digital record?

This is a complicated issue.  I see a distinction between "computer-generated identifier assigned to represent the conceptual object" (e.g., a UUID), and "ID of the digital record containing data about the specimen".  It's a subtle, but important, distinction.

For example, I have a field that automatically assigns a UUID to every instance of MaterialSample in our databases.  Although the UUID was "born" digitally, and does indeed uniquely represent the digital record for the physical object; the intention of the the identifier is that it represents the physical thing; not the digital record for the thing.  So, when I generate an IPT dataset that is shared with GBIF, and the contents of that record are captured in the GBIF aggregated dataset, the UUID is retained.  If the identifier was for the digital record, then it should *not* be transmitted to GBIF, because the record in GBIF is actually a *different* digital record, so would need to have a *different* identifier to represent that different digital record.

Indeed, I think that our community only very rarely assigns or uses unique identifiers for digital records, and when they do, it should be extremely explicit (e.g., "this is the identifier assigned to the Bishop Museum database record for this specimen, and this is the identifier assigned to the GBIF database record for the same specimen, [etc.]")

Yes, catalog numbers and accession numbers and sheet numbers and other human-friendly identifiers can be thought of as additional identifiers assigned to the same physical object, and that's fine -- many physical and abstract instances captured as data records in databases have more than one unique(ish) identifier assigned to them (e.g., see [bioguid.org](http://bioguid.org)). 

But my point is, I think we need to be extremely explicit when trying to distinguish identifiers intended to represent the physical (or abstract) object, vs. identifiers intended to represent a particular digital record about that object.

As to the issue at hand, I'm fine leaving the definition unchanged, mostly for the reasons mentioned by @tucotuco.  My personal philosophy of persistent identifiers matches closely the sentiments expressed by @dagendresen.

**Comment by Jegelewicz** [comment]
> But my point is, I think we need to be extremely explicit when trying to distinguish identifiers intended to represent the physical (or abstract) object, vs. identifiers intended to represent a particular digital record about that object.

See also But my point is, I think we need to be extremely explicit when trying to distinguish identifiers intended to represent the physical (or abstract) object, vs. identifiers intended to represent a particular digital record about that object.

**Comment by Jegelewicz** [comment]
Stephen R. Jutta B. and Teresa M. discussed this at length on 2022-03-31 during working hour.

1. Physical samples WILL have more than one identifier - how do you choose the one that goes here? (Jutta discuss identifier class)
2. Are we commingling identifiers for the physical object and the digital representation?
3. Do we need a term for the identifier for the digital representation of the MaterialSample?
4. Identifiers have/need their own set of metadata: who issued them?, who applied them?, are they verified?

**Comment by Jegelewicz** [comment]
Also discussed today with @deepreef 

See http://bioguid.org/about

What will happen when institutions have multiple sample (skin,skeleton, tissue) with only a single identifier (catalog number)? We will need methods for making the "split" easy?

**Comment by dr-shorthair** [comment]
I'd suggest being very clear about which IDs are keys, in what context; 
and which 'IDs'  are being stored as 'annotations' related to some prior context.

**Comment by Jegelewicz** [comment]
closing as no change needed and identifier class is out of scope for this Task Group
