### ISSUE TITLE
Proposed clarifications for "organism" in dwc:Organism

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/material-sample#23]
The current definition of ```dwc:Organism```: A particular organism or defined group of organisms considered to be taxonomically homogeneous.

Do we need to clarify "organism" as used in this definition?

**Comment by Jegelewicz** [comment]
Any organic, living system that functions as an individual entity.

@Jegelewicz in https://github.com/tdwg/material-sample/issues/21#issuecomment-968064085

**Comment by Jegelewicz** [comment]
Oxford Languages says:

"an individual animal, plant, or single-celled life form"

Webster's Unabridged Dictionary says:
"an individual constituted to carry on the activities of life by means of parts or organs more or less separate in function but mutually dependent : a living being"

@tucotuco in https://github.com/tdwg/material-sample/issues/21#issuecomment-968100895

**Comment by baskaufs** [comment]
Due to a rush of work, I have not been able to keep up with the huge mass of comments on GitHub. I'm going to try to get caught up today. However, I'm somewhat alarmed with the discussion around redefining the `dwc:Organism` class. 

Just for background, I'm the person who proposed and spent four years pushing for having a `dwc:Organism` class (see https://github.com/darwin-sw/dsw/wiki/TdwgContentEmailSummary for context). I also led the 2014 effort to deprecate the Darwin Core Type vocabulary (http://rs.tdwg.org/dwc/dwctype/) and clarify the meanings of all of the "main" classes in Darwin Core, including considering in those definitions the existence of the `dwc:Organism` class (not included in the original definitions). 

The `dwc:Organism` class as it currently exists serves a fundamentally different role from the classes that are used primarily as values for `dwc:basisOfRecord` (e.g. `dwc:PreservedSpecimen`, `dwc:LivingSpecimen`, not sure about `dwc:MaterialSample`). It's primary role, at least as envisioned at the time of its birth, was to serve as a node to link `dwc:Occurrences` with `dwc:Identifications`. (The genesis of my efforts to push for having a class to serve in this role is in the 2010 paper https://doi.org/10.17161/bi.v7i1.3664 .) Prior to having the organism class, the only option was to link occurrences directly to identifications. This was problematic in cases where organism were "resampled" by capture/release, camera traps, attached sensors, etc. It was possible at the time to group multiple occurrences of the same organism using `dwc:individualID` (now `dwc:organismID`), but not possible to link a single identification to that organism, because Darwin Core didn't recognize that organisms existed as a class.

After a punishing mailing list discussion that went on for months (see the link above for some of it) and that involved @deepreef heavily, a consensus was reached about how to define `dwc:Organism`. The definition was broadened to include entities that could be resampled and that were taxonomically homogeneous enough to be assigned an identification regardless of whether they were individual biological organisms or not. So not only could biological organisms fall into this group, but groups of organisms that were monitored, such as wolf packs, clonal organisms (e.g. aspen clonal colonies), and colonial organisms (like corals) were also included even if they did not fall into the definition of a single biological organism.

So I would not say that this definition is "circular" because a member of the `dwc:Organism` class is not synonymous with an "organism". If it's desirable to come up with a more precise definition of "organism" (lower case) as used within the definition of `dwc:Organism` (what seems to be recommended in this particular issue), perhaps linking to a well-known ontology in the comments, or even within the defintion, would be an option. But `dwc:Organism` can't just be redefined as a part of this effort without considering its history and how it is being currently used along with `dwc:organismScope` to serve in the "node" role I've described here. It's not just a descriptive term to indicate the type of thing something is.

**Comment by tucotuco** [comment]
Thanks @baskaufs . I agree wholeheartedly. Another thing I would like to put to rest in these discussions is the idea of a continuum from dwc:Organism to dwc:Taxon. THAT would be circular. To me there is no continuum that reaches Taxon, they are fundamentally different concepts that are commonly conflated. I think it is important for this group and it's outputs to take a solid stand on that.

**Comment by Jegelewicz** [comment]
A living specimen is, of course, an organism.  I think the key distinction between the two concepts is that LivingSpecimen is a kind of MaterialSample, whereas the DwC Organism class is intended to represent an organism that is inferred to exist or to have existed (past tense).  The critical role for the Organism class is that the concept and in particular the property `dwc:OrganismID` ties together multiple occurrence records that derive from the same organism.  Other properties derive from the Organism class (most importantly what taxon the organism represents), but in our "shorthand" practice they are commonly recorded as properties of something that has a 1:1 relationship with organism, i.e., the Occurrence or the whole-animal MaterialSample.

@stanblum in https://github.com/tdwg/material-sample/issues/21#issuecomment-968354403

**Comment by smrgeoinfo** [comment]
So...
Organism is a class (Kind of ' organic, living system that functions as an individual entity')
MaterialSample is an instance that could be an instance of some Organism class ?

**Comment by stanblum** [comment]
Sorry, Steve; I wasn't trying to start a backslide. (I just went fishing
for a definition of the term as used in common language.)  I agree with all
those points, especially that the "organism" concept is critical to our
work, particularly as the linking node to resampled/re-observed things, and
that samples and observations of multiple individuals can serve as the
"organism" class.  I would not concede that organism blends imperceptibly
into taxon.  Back in 2014 I had my own punishing work schedule and didn't
have the time to participate in those discussions.

**Comment by dr-shorthair** [comment]
Cross-referencing the ‘Sample’ discussion – I believe that would make ‘Occurrence’ a sample of the ‘Organism’ 

```turtle
:Org987 a dwc:Organism . 

:Occ123 a dwc:Occurrence ;
                sosa:isSampleOf :Org987 . 
```

**Comment by stanblum** [comment]
dr-shorthair wrote:
> Cross-referencing the ‘Sample’ discussion – I believe that would make ‘Occurrence’ a sample of the ‘Organism’

I would say the Occurrence is equivalent to sampling (verb), not the result, sample, a noun.  Organisms exist all over the place, but they don't become part of science until observed or sampled.  The input-what (organism), when, where, who, and the output what (sample and data, or just data) are all pretty integral to the concept.

**Comment by dr-shorthair** [comment]
Yes. Completing the graph (using SOSA predicates):
```turtle
:Sg567 a sosa:Sampling ; 
    sosa:hasResult :Occ123 ; 
    sosa:hasFeatureOfInterest :Org987 .
```

**Comment by dr-shorthair** [comment]
Then later on when you start making observations:
```turtle
:Ob456 a sosa:Observation ;
    sosa:hasFeatureOfInterest :Occ123 ;
    sosa:hasUltimateFeatureOfInterest :Org987 ;
    sosa:observedProperty "taxonIdentification" ;
    sosa:hasResult <https://linaeus.org/swirgle> ; 
    sosa:madeBySensor <https://orcid.org/0000-0002-3884-3421> ;
    sosa:usedProcedure <https://bioclass.org/YTG357/> ;
.
```

**Comment by deepreef** [comment]
I would also like to echo the pleas by @baskaufs not to change the definition of `dwc:Organism`.  However, we clearly need a little bit of elaboration or clarification.  For example:  Is a fossil an `Organism`?  If not, then what about a freshly dead bird on the side of the road?

> Another thing I would like to put to rest in these discussions is the idea of a continuum from dwc:Organism to dwc:Taxon. THAT would be circular. To me there is no continuum that reaches Taxon, they are fundamentally different concepts that are commonly conflated. I think it is important for this group and it's outputs to take a solid stand on that.

Yes, agreed -- there is not a "continuum" from `Organism` to `Taxon`. But there are some subtleties here that need to be clarified to avoid further confusion.  A single instance of `dwc:Organism` may include more than one individual, and indeed may include many, many, many individuals.  The only constraint is that every individual member of the single instance of `Organism` must belong to (or at least, asserted to belong to) the same instance of `dwc:Taxon`.  So technically one could create a single instance of `dwc:Organism` that includes every single individual of a Taxon.  This does not make it the *same* as the taxon, but does provide a mechansim to document things like absences in the form of `dwc:Occurrence` instances.

**Comment by Jegelewicz** [comment]
closing for focus on MaterialSample and properties
