### ISSUE TITLE
sampled Feature Type - new property of MaterialSample

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/material-sample#28]
<html><body>

Term Name  dwc:sampledFeatureType
--
Label | Response
 -- | -- 
Term IRI | 
Modified | 
Term version IRI | 
Label | sampledFeatureType
Definition | Property to specify the broad context that a sample is intended to represent.
Notes | Recommended best practice is to use controlled value strings from the controlled vocabulary designated for use with this term, listed at **need**. For details, refer to **need**
Examples | **create a list from the controlled vocabulary**
ABCD equivalence | [RecordBasis](https://terms.tdwg.org/wiki/abcd2:RecordBasis) ([/DataSets/DataSet/Units/Unit/RecordBasis](https://terms.tdwg.org/wiki/abcd2:RecordBasis))
Type | Property
Executive Committee decision | 

</body>
</html>

We will also need:

Label | Response
 -- | -- 
Submitter: | TDWG MaterialSample Task Group
Efficacy Justification (why is this change necessary?): | 
Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): | 
Stability Justification (what concerns are there that this might affect existing implementations?): | 
Implications for dwciri: namespace (does this change affect a dwciri term version)?: | 
Organized in Class (e.g., Occurrence, Event, Location, Taxon): | MaterialSample
Refines (identifier of the broader term this term refines; normative): | 
Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): |

**Comment by smrgeoinfo** [comment]
Definition: property to specify the broad context that a sample is intended to represent.

Notes: a material sample is distinguished from other things by the fact that the intention of a material sample is to represent some physical 'feature of interest' in the world.  This can be challenging because contexts are typically nested, and can be defined based on different perspectives. An archaeologist would view the context of a sample collected from a profile in a trench differently than a soil scientist.  The context for a sample of material from the gut of an animal could be considered to be the particular animal sampled, the species of the animal, or the environment in which the animal lived.
It is expected that to the extent possible this property should represent the intention of the original collector of the sample. Other information in the sample description should allow inferences about other broader or narrower contexts of interest.

**Comment by dagendresen** [comment]
Maybe ABCD equivalence = [RecordBasis](https://terms.tdwg.org/wiki/abcd2:RecordBasis) ([/DataSets/DataSet/Units/Unit/RecordBasis](https://terms.tdwg.org/wiki/abcd2:RecordBasis))
Definition: A controlled vocabulary indicating what the unit record represents.
Notes: Note that the element {{{SourceReference}}} provides for the case that the record is based on a publication.

**Comment by smrgeoinfo** [comment]
Note that materialEntity is much broader that materialSample.  According to our definition, these are materialEntities: The sun, the Acropolis, the West Antarctic Ice sheet, a particular atom identified using a atom probe microscope.  
As we discussed in our workgroup, what makes a materialEntity a sample is the intention that it is representative of something we are interested in. A materialEntity type vocabulary would have a scope covering every material object in the universe-- probably outside of our workgroup purview.

**Comment by Jegelewicz** [comment]
closing as out of scope
