### ISSUE TITLE
Other Deliverable - preparations review

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/material-sample#7]
> Task Group will make a recommendation [...] as to which class in the Darwin Core standard these properties belong which may also include recommendations for terms being revised, added, disambiguated, or deprecated. Depends upon definitions provided [in primary deliverable].

# Current Darwin Core Placement/Definition

http://rs.tdwg.org/dwc/terms/preparations

this term is a **property** of **Occurrence**

## Defintion
A list (concatenated and separated) of preparations and preservation methods for a specimen.

## Examples
fossil, cast, photograph, DNA extract, skin | skull | skeleton, whole animal (ETOH) | tissue (EDTA)

## Comments
Recommended best practice is to separate the values in a list with space vertical bar space ( \| ).

## See also 
Change term - preparations: https://github.com/tdwg/dwc/issues/346

**Comment by smrgeoinfo** [comment]
This only applies to material sample.   Material entity is much broader.

**Comment by Jegelewicz** [comment]
> This only applies to material sample.

I'm not sure that I agree. It seems like things can be prepared without being `A physical result of a sampling (or subsampling) event.` A lot of stuff in collections was not "sampled" in that way.

Again, I think that `preparations` could actually apply to more than one class. In my opinion, all of these could have preparations

MaterialEntity
MaterialSample
PreservedSpecimen
FossilSpecimen
LivingSpecimen (do cuttings grown into new things or clones count as `preparation`?)
MachineObservation (.jpg, printed photograph, tape recording, etc.)

I would actually recommend not using the term `specimen`, but that's for after we decide if MaterialEntity could use this property or not. I would also prefer to see this not be plural and instead add as many `preparation` properties to whatever is "prepared" as necessary.

**Comment by tucotuco** [comment]
More unattributed dirty laundry...

The top 20 values for preparations in HUMAN_OBSERVATION records in the July 2022 snapshot of GBIF, in descending order of frequency, were:
Frozen
95% ethanol
NA
photograph
Data
NO APLICA
Fresh
Colecta definitiva: Ejemplar completo en Etanol
90% ethanol
ETOH
media
NO DISPONIBLE
Animal completo (ETOH)
RNA stabilization buffer
Animal entero en sobre
Fotografía
Alfiler
Lugol preserved samples
Técnicas estándar de muestras botánicas para un herbario
DNA extract

The top 20 values for preparations in MACHINE_OBSERVATION records in the July 2022 snapshot of GBIF, in descending order of frequency, were:
Fotografía
digitised .wav
Photograph
Corte de audio
Polyester
photograph
fotografía
Film
SEM micrograph
Acetate
Photograph:b&w
Tarjeta SD
photograph-digital - 1
Google Drive
pen and ink
Image only; Biorepository
Ink
Microslide
digitised .aif
default - 1

**Comment by Jegelewicz** [comment]
> preparations and preservation methods
> whole animal (ETOH) 

it seems like there should be two terms?

preparation - what you have - whole animal
preservation - how it is preserved - ETOH

Should we take the time now to split these up?

**Comment by dagendresen** [comment]
I think yes, that we would want to move the term(s) to MaterialEntity, and split into two terms preparation and preservation.

**Comment by Jegelewicz** [comment]
Move to MaterialEntity, but note that this needs to be clarified and all of the dimensions related to Material need to be detailed and classified. But this is a task for another group.

**Comment by Jegelewicz** [comment]
@cboelling - meant and used to describe material in the context of an occurrence, but it is vague and the definition is more of an instruction than a definition. Needs to be divided and given proper definitions for actual material properties - a task for another group. Deprecate and get a better set of terms.

**Comment by Jegelewicz** [comment]
@tucotuco - Dividing occurrence from the stuff that came from it and for now we will have a term that is overloaded, but we need someone else to work on that.

**Comment by Jegelewicz** [comment]
Andy Bentley tried to do this separation (Arctos has some of this too). But nothing has ever been formalized. Again, a project for another day!

**Comment by stanblum** [comment]
Everyone on the call today (Teresa, Stan, Jutta, Christian, John) agreed (no objections) that dwc:preparations should be _organized_ under MaterialEntity rather than Occurrence, and that developing a materialEntity extension -- to rigorously address the things (parts), treatment (preparations), and storage regime -- would be a timely (overdue) project, but it's out of scope for the MaterialSample project.  In the short-term, some clarification of the syntax and examples would be useful.

**Comment by deepreef** [comment]
Many thanks for sharing this!  I apologize for not being able to attend the last couple meetings (I was/am travelling during both). 

One thing I may have missed, but am hoping to get clarity on:  Does the term `MaterialEntity` **replace** `MaterialSample`?  Or will they both be maintained as related by distinct terms (e.g., class/subclass; whatever)?  The practical implication of this has to do with the LARGE number of `materialSampleID` values I have already generated.  Can I present these as `materialEntityID` values going forward?  Or do I need to mint *another* set of ID values to present as `materialEntityID`, while maintaining my existing values as `materialSampleID`?

I know what the purist answer is; but keep in mind that when I assign identifiers to things, those identifiers are explicitly intended to represent the actual "thing" (physical or abstract/conceptual); **not** the "data record for the thing". 

P.S. I understand that this is not the right issue to ask this question in (preparations), but as I said, I am travelling, with tenuous internet access, and it was easy to reply to Stan's post that showed up in my email inbox, and I don't really have the time to hunt down the correct issue to post this to...

**Comment by Jegelewicz** [comment]
> Does the term MaterialEntity replace MaterialSample? 

No - see https://github.com/tdwg/material-sample/blob/main/review%20package/MaterialEntity.md

I don't feel that I can confidently answer your other questions, but @tucotuco said he will weigh in here.

**Comment by deepreef** [comment]
Excellent!  Thank you, @Jegelewicz !  This is extremely helpful.  I knew this New Term Request existed, but haven't had he time to read it, and I should have done that before posting here, above.  This New Term Request is extremely well written, and answers most of my questions!  I will articulate my question about IDs over there.

Again, thansk for the redirection, and apologies for cluttering this thread.

**Comment by cboelling** [comment]
@deepreef:
> Can I present these as `materialEntityID` values going forward? Or do I need to mint _another_ set of ID values to present as `materialEntityID`, while maintaining my existing values as `materialSampleID`?

That individual `xyzID` properties are present in DwC has puzzled me for some time. I think it might, as other features of DwC, the consequence of the design - the serialization, actually - of simple DwC archives (but maybe I miss an important aspect concerning the expressivity). I think that any value that has been minted and used as value in a statement including `dwc:materialSampleID` can equally well be used with `dwc:materialEntityID` because, even if it is not presented in DwC, `dwc:MaterialSample` is a subclass of `dwc:MaterialEntity`. An instance of `dwc:MaterialSample` is also an instance of `dwc:MaterialEntity` (but the opposite isn't true).

**Comment by Jegelewicz** [comment]
Perhaps there should be an identifier class in Darwin Core as the Latimer Core people have pioneered?

https://github.com/tdwg/rs.tdwg.org/blob/latimer/process/page_build_scripts/index.md#ltc_Identifier

![image](https://user-images.githubusercontent.com/5725767/233680023-47735063-a2a1-4901-9d89-f08bda7e3250.png)

We tried to discuss this at the meeting in March - but it was deemed out of scope (and it is) - but this is something that goes right along with the question of what are we doing? Are we creating a bunch of terms or a structure in which they can/should be used?

**Comment by baskaufs** [comment]
For background on the xID terms, I'd recommend taking a look at [section 2.6 of the Darwin Core RDF Guide](https://dwc.tdwg.org/rdf/#26-darwin-core-id-terms-and-rdf-normative). In flat tables, the ID terms are used both as a primary key for the entities represented by the row in the table and also as a sort of foreign key linking to related resources that may be described in other tables. This design pattern is useful in this context, but has certain problems when people want to say that the ID terms are always "about" the subject resource. That's why they aren't recommended for use in RDF where their semantics are unclear. In RDF, it makes the most sense to use dcterms:identifier to state the identifier of the subject resource and dwciri: terms to link out to related resources. The semantics of those terms aren't ambiguous. This is actually the normative guidance within Darwin Core and departing from it would require a coordinated change to the standard.

**Comment by Jegelewicz** [comment]
> In RDF, it makes the most sense to use dcterms:identifier to state the identifier of the subject resource and dwciri: terms to link out to related resources.

I can't decide if it is funny or sad that I (and I am guessing most collection managers) have absolutely no idea what this means and I wonder what implications that has for sharing the rich data available in natural history collections.

**Comment by baskaufs** [comment]
I apologize for my tone in the previous, comment, Teresa. I was not trying to insinuate that anyone doesn't belong in the conversation. 

The point I was trying to make was that we are modifying a technical specification and sometimes that's going to get complicated. Maintaining Darwin Core is particularly difficult because it is used in so many ways and therefore has to satisfy so many different kinds of users. Some people are only concerned with using it in spreadsheets, while others want to use it to create linked data or ontologies. So it's a balancing act to design it in such a way that it works for all use cases. A solution that seems obvious for a spreadsheet user may have unintended consequences for someone who wants to build a linked data system based on RDF. A solution that may seem obvious to the RDF/Linked data user may make things too complicated or unintelligible for spreadsheet users. We have to try to strike a balance between the two. 

The reason we have a Technical Architecture Group is to be on the lookout for potential problems that might make what one group proposes cause problems for another. As the TAG chair, I have to be on the lookout for those kinds of problems and bring them up when I notice them. We have technical experts on the TAG to work out solutions so the rank and file don't have to struggle with them. That doesn't mean that the contributions of non-TAG people aren't important -- they are critically important to make sure that we are building something that's really useful to non-technical users.  

I greatly value your contributions, both in terms of the ideas that you suggest as well as the heavy lifting that you do to keep the Material Sample Task Group together and moving. So I'm sorry if what I said made you feel excluded.

**Comment by baskaufs** [comment]
I understand your feelings on this. When I first started working in TDWG, all of this was foreign to me and it's taken me many years to get to the level of understanding I now have (painfully, with frustration and mostly by teaching myself). 

I don't think every user should need to have a detailed knowledge of the technical details to USE the standards. I think it is recognized that we still have a way to go in helping bring people up to speed on what they actually need to know, although there has been work put into things like Darwin Core Hour presentations and user guides. But I don't think there is any getting around the fact that people involved in DEVELOPING the standards will have to face up to dealing with some of the technical details. Hopefully those who do have the technical background will be patient and helpful with those who don't, just as those with the biological domain knowledge will have to be patient and helpful with the tech people who don't have that background. 

I don't want to minimize the problem that you raise, but I think there are some places where there's been a really great collaboration between technical and biological folks who've figured out how to work together to get things done. I've experienced this in the Humboldt Extension TG and I think it's similar in the Latimer Core TG. So I do have hope that if we keep trying and are patient, we can succeed in building useful vocabularies and tools.

**Comment by Jegelewicz** [comment]
added to review package - https://github.com/tdwg/material-sample/blob/main/review%20package/preparations.md

**Comment by Jegelewicz** [comment]
submitted to dwc repo - https://github.com/tdwg/dwc/issues/452

**Comment by Jegelewicz** [comment]
change complete - https://github.com/tdwg/dwc/issues/452
